import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeSnapshot,scopeBranches,csvCell,readScopedSnapshot,SnapshotRequestGuard} from '../src/lib/financial.ts';
const line={productId:'p',productName:'Coffee',quantity:2,salePrice:4,purchasePrice:2};
const record={id:'s',items:[line],currency:'LBP',exchangeRate:89500,date:'2026-10-01T10:00:00Z',cashierName:'Cashier',subtotal:8,total:716000};
const row={business_id:'b',branch_id:'br',record};
const snapshot=()=>structuredClone({products:[],sales:[row],refunds:[{...row,record:{...record,id:'r',saleId:'s',items:[{...line,quantity:1}],totalRefunded:358000,total:undefined,subtotal:undefined,date:'2026-10-02T10:00:00Z'}}],historical:{sales:[{id:'legacy',total:10,business_id:'b',branch_id:'br'}],sale_items:[],refunds:[],refund_items:[]}});
test('normalizes mixed settlement currency and subtracts refunds on refund date',()=>{const d=normalizeSnapshot(snapshot(),'b',['br']);assert.equal(d.sales.reduce((s,r)=>s+r.total,0),4);assert.equal(d.sales.filter(r=>r.kind==='sale').length,1);assert.equal(d.sales.find(r=>r.kind==='refund')?.date,'2026-10-02T10:00:00Z');assert.equal(d.saleItems.reduce((s,i)=>s+i.quantity*(i.sale_price-i.purchase_price),0),2);});
test('preserves original history separately without inventing transactions',()=>{const raw=snapshot();const before=JSON.stringify(raw);const d=normalizeSnapshot(raw,'b',['br']);assert.deepEqual(d.historical.sales,[{id:'legacy',total:10,business_id:'b',branch_id:'br'}]);assert.equal(JSON.stringify(raw),before);});
test('rejects mismatched business and branch scope',()=>{assert.throws(()=>normalizeSnapshot(snapshot(),'other',['br']));assert.throws(()=>normalizeSnapshot(snapshot(),'b',['other']));});
test('rejects missing exchange rates and nonfinite values',()=>{const d=snapshot();d.sales[0].record.exchangeRate=0;assert.throws(()=>normalizeSnapshot(d,'b',['br']));d.sales[0].record.exchangeRate=89500;d.sales[0].record.total=NaN;assert.throws(()=>normalizeSnapshot(d,'b',['br']));});
test('rejects incorrect totals and duplicate records',()=>{const d=snapshot();d.sales[0].record.total=1;assert.throws(()=>normalizeSnapshot(d,'b',['br']));const e=snapshot();e.sales.push(e.sales[0]);assert.throws(()=>normalizeSnapshot(e,'b',['br']));});
test('scopes empty and unavailable branches without unscoped queries',()=>{assert.deepEqual(scopeBranches([]),[]);assert.deepEqual(scopeBranches(['a'],'b'),[]);assert.deepEqual(scopeBranches(['a','a']),['a']);});
test('CSV escapes commas quotes and spreadsheet formulas',()=>{assert.equal(csvCell('a,"b"'),'"a,""b"""');assert.equal(csvCell('=1+1'),'"\'=1+1"');});
test('financial snapshots retain more than the REST row limit',()=>{const d=snapshot();d.refunds=[];d.sales=Array.from({length:1101},(_,i)=>({...row,record:{...record,id:String(i)}}));assert.equal(normalizeSnapshot(d,'b',['br']).sales.length,1101);});

test('inactive products are excluded while negative stock remains visible for review',()=>{const raw={...snapshot(),products:[{id:'inactive',business_id:'b',branch_id:'br',is_active:false,stock:8},{id:'negative',business_id:'b',branch_id:'br',is_active:true,stock:-2}]};const d=normalizeSnapshot(raw,'b',['br']);assert.deepEqual(d.products.map(p=>p.id),['negative']);assert.equal(d.products[0].stock,-2);});
test('USD sales and LBP refunds retain distinct settlement amounts and original cost',()=>{const raw=snapshot();raw.sales[0].record.currency='USD';raw.sales[0].record.total=8;const d=normalizeSnapshot(raw,'b',['br']);assert.equal(d.sales.reduce((n,s)=>n+s.total,0),4);assert.equal(d.sales.find(s=>s.kind==='refund')?.settlement_amount,-358000);assert.ok(d.saleItems.every(i=>i.purchase_price===2&&i.cost===2));});

test('empty or invalid branch selections never issue an unscoped database request',async()=>{let calls=0;const request=async()=>{calls++;return {data:snapshot(),error:null};};await readScopedSnapshot(request,'b',[]);await readScopedSnapshot(request,'b',['br'],'foreign');assert.equal(calls,0);});
test('snapshot request uses exact business and allowed branch scopes',async()=>{let args:unknown;const data=await readScopedSnapshot(async a=>{args=a;return {data:snapshot(),error:null};},'b',['br','br'],'all');assert.deepEqual(args,{p_business_id:'b',p_branch_ids:['br']});assert.equal(data.sales.length,2);});
test('database errors and malformed snapshots fail closed rather than return partial totals',async()=>{await assert.rejects(readScopedSnapshot(async()=>({data:snapshot(),error:{message:'offline'}}),'b',['br']),/offline/);await assert.rejects(readScopedSnapshot(async()=>({data:{products:[]},error:null}),'b',['br']));});
test('inventory snapshot reads every active product beyond the REST cap',async()=>{const raw={...snapshot(),products:Array.from({length:1101},(_,i)=>({id:String(i),business_id:'b',branch_id:'br',is_active:true,stock:1}))};const d=await readScopedSnapshot(async()=>({data:raw,error:null}),'b',['br']);assert.equal(d.products.length,1101);});

test('slow old-scope and superseded requests cannot replace the current snapshot',async()=>{const guard=new SnapshotRequestGuard();guard.activate('b/one');const first=guard.begin('b/one');const newer=guard.begin('b/one');assert.equal(guard.isCurrent(first),false);assert.equal(guard.isCurrent(newer),true);guard.activate('b/two');assert.equal(guard.isCurrent(newer),false);const current=guard.begin('b/two');await Promise.resolve();assert.equal(guard.isCurrent(current),true);});
test('unknown stock fails closed rather than being converted to zero',()=>{const raw={...snapshot(),products:[{id:'unknown',business_id:'b',branch_id:'br',is_active:true,stock:null}]};assert.throws(()=>normalizeSnapshot(raw,'b',['br']));});

test('refund amounts remain numeric in CSV while textual formulas are neutralized',()=>{assert.equal(csvCell(-358000),'"-358000"');assert.equal(csvCell('-SUM(A1:A2)'),'"\'-SUM(A1:A2)"');});

test('CSV neutralizes whitespace-prefixed spreadsheet formulas',()=>{assert.ok(csvCell('  =1+1').startsWith(String.fromCharCode(34,39)));});

test('refund item cost and cumulative quantity must match the immutable original sale',()=>{const raw=snapshot();raw.refunds[0].record.items[0].purchasePrice=99;assert.throws(()=>normalizeSnapshot(raw,'b',['br']),/immutable/);const excessive=snapshot();excessive.refunds.push({...structuredClone(excessive.refunds[0]),record:{...structuredClone(excessive.refunds[0].record),id:'r2'}});excessive.refunds.push({...structuredClone(excessive.refunds[0]),record:{...structuredClone(excessive.refunds[0].record),id:'r3'}});assert.throws(()=>normalizeSnapshot(excessive,'b',['br']),/exceeds/);});
test('duplicate item lines and foreign historical scope fail closed',()=>{const raw=snapshot();raw.sales[0].record.items.push(structuredClone(raw.sales[0].record.items[0]));assert.throws(()=>normalizeSnapshot(raw,'b',['br']),/Duplicate/);const foreign=snapshot();foreign.historical.sales[0]={id:'foreign',total:10,business_id:'other'} as typeof foreign.historical.sales[number];assert.throws(()=>normalizeSnapshot(foreign,'b',['br']),/Historical/);});
